// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_eQf1OffPe2hgSdqIH1koSD-I8U7qAqA',
    appId: '1:1092801679124:web:7e7e03ab18a3e8b0ebbc01',
    messagingSenderId: '1092801679124',
    projectId: 'quick-foodie-a46e5',
    authDomain: 'quick-foodie-a46e5.firebaseapp.com',
    storageBucket: 'quick-foodie-a46e5.appspot.com',
    measurementId: 'G-XQEJ98PLXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDiCfaotx53CnVcZG2LdWXefv9K2ENhs',
    appId: '1:1092801679124:android:90a59395fb41fe04ebbc01',
    messagingSenderId: '1092801679124',
    projectId: 'quick-foodie-a46e5',
    storageBucket: 'quick-foodie-a46e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRZeqrVHz4_8bWZuf0Wzfu2j4sCdXTKQw',
    appId: '1:1092801679124:ios:e367d015b908be60ebbc01',
    messagingSenderId: '1092801679124',
    projectId: 'quick-foodie-a46e5',
    storageBucket: 'quick-foodie-a46e5.appspot.com',
    iosBundleId: 'com.example.quickFoodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRZeqrVHz4_8bWZuf0Wzfu2j4sCdXTKQw',
    appId: '1:1092801679124:ios:380afcdc33b1648bebbc01',
    messagingSenderId: '1092801679124',
    projectId: 'quick-foodie-a46e5',
    storageBucket: 'quick-foodie-a46e5.appspot.com',
    iosBundleId: 'com.example.quickFoodie.RunnerTests',
  );
}
